server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/songsMS/rest/auth/**
        - id: songs-service
          uri: http://localhost:8082/
          predicates:
            - Path=/songsMS/rest/songs/**
        - id: songs-service
          uri: http://localhost:8082/
          predicates:
            - Path=/songsMS/rest/songlists/**
        - id: lyrics-service
          uri: http://localhost:8083/
          predicates:
            - Path=/songsMS/rest/lyrics/**


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
